### PR TITLE
Get cabal matching up with the source files.

### PR DESCRIPTION
**Pull request by seagreen**
Remove src/Twilio/Types/TwilioT.hs since it wasn't being used.

Add Twilio.Types.Issue to the other-modules section of the cabal file.
This prevents the following bug from occuring when other application try
to use the twilio library:

```
<no location info>:
    <command line>: can't load .so/.DLL for: /home/traveller/code/fanjam/fanjam-api-servant/api/.cabal-sandbox/lib/x86_64-linux-ghc-7.10.1/twili_HwROPXwVgDK34Z4up189Jn/libHStwilio-0.1.2.1-HwROPXwVgDK34Z4up189Jn-ghc7.10.1.so (/home/traveller/code/fanjam/fanjam-api-servant/api/.cabal-sandbox/lib/x86_64-linux-ghc-7.10.1/twili_HwROPXwVgDK34Z4up189Jn/libHStwilio-0.1.2.1-HwROPXwVgDK34Z4up189Jn-ghc7.10.1.so: undefined symbol: twilizuHwROPXwVgDK34ZZ4up189Jn_TwilioziTypesziIssue_zdfEqIssue_closure)
[ 6 of 26] Compiling Web.Fanjam.Internal.Core ( Lib/Web/Fanjam/Internal/Core.hs, dist/build/Web/Fanjam/Internal/Core.o )

<no location info>:
    ghc: panic! (the 'impossible' happened)
  (GHC version 7.10.1 for x86_64-unknown-linux):
    Dynamic linker not initialised

Please report this as a GHC bug:  http://www.haskell.org/ghc/reportabug
```

### CODE REVIEW

**Comment by seagreen** [comment]
I think this is the last PR for now:)

**Comment by markandrus** [comment]
Oh my, good catch! Thanks as always @seagreen. Still waiting on travis-ci builds to work (for an unrelated reason it looks like)... I'd like to get a green build by this evening before pushing to Hackage.

**Comment by seagreen** [comment]
You're welcome. Re: waiting on the build: that sounds good to me.

**Comment by markandrus** [comment]
Hey @seagreen, build is working now and I've uploaded [twilio 0.1.3.0](https://hackage.haskell.org/package/twilio-0.1.3.0) to Hackage. Though I must admit I only glanced over `Twilio.Types.Issue` being added to `other-modules` and not `exposed-modules`—can you explain more why you needed this? I'd like to move it to `exposed-modules` in subsequent releases.

**Comment by seagreen** [comment]
If it's not included in either `exposed-modules` or `other-modules` it gives me a build error in my application that uses twilio-haskell. I don't care which one though, so if it's meant to be exposed by all means move it to `exposed-modules`.

It's strange behaviour. You would expect that leaving it out would cause twilio-haskell to fail to build, but instead it causes applications using twilio-haskell to fail to build. Weird.

**Pull request merged**
