### PR TITLE
Add the ability to POST text messages.

### PR DESCRIPTION
**Pull request by seagreen**

### CODE REVIEW

**Comment by seagreen** [comment]
Example code (with fake phone numbers):

```
module Main where

import Control.Monad.IO.Class (liftIO)
import System.Environment (getEnv)
import Twilio.Message as Message
import Twilio.Messages as TM
import Twilio.Types

main :: IO ()
main = do
  msg <- runTwilio' (getEnv "ACCOUNT_SID")
                    (getEnv "AUTH_TOKEN")
         $ TM.post msg
  print (Message.sid msg)

  where
    msg = TM.SendMessage
      { TM.sendTo = "+19193238866"
      , TM.sendFrom = "+13302227070"
      , TM.sendBody = "test message"
      }
```

**Comment by seagreen** [comment]
Let me know what you think of the PR. I tried to error on the side of not making big changes.

For instance, since we now have a `postForAccount`, it would make sense for symmetry reasons to change the old `requestForAccount` to `getForAccount`, but I left it alone because I didn't want my first real PR to change every file in the program.

**Comment by markandrus** [comment]
Thanks!

> it would make sense for symmetry reasons to change the old `requestForAccount` to `getForAccount`

I agree. I think it's fine to leave as is, since I anticipate more changes... especially when #1 happens.

Another open question, and not necessarily a blocker to merging this PR: do we want to name the data types for POSTing to resources according to their use cases (for example, `SendMessage`) or more generically (for example, `POSTMessageRequestBody`). I'm not sure at this time.

Feel free to add yourself to the AUTHORS file.

**Comment by seagreen** [comment]
I'd definitely be fine with changing the name `SendMessage`, how about `PostMessageRequest` or `PostMessage` (or either of those with "Post" in all caps)?

**Comment by seagreen** [comment]
Re: AUTHORS: Thanks! I amended the commit to add myself in.

**Comment by markandrus** [comment]
Hmm, I guess I like `PostMessage`. Once you amend with that change I'll merge.

**Comment by seagreen** [comment]
Sweet, I amended the commit to use `PostMessage`.

**Comment by markandrus** [comment]
Thanks, @seagreen!

**Pull request merged**
